server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name jlr-doip.local 192.168.0.175 _;
    root /var/www/ebu-site;
    index index.html;
    charset utf-8;
    access_log off;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_comp_level 4;
    gzip_types text/plain text/css application/javascript application/json application/xml text/xml image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /robots.txt {
        try_files $uri =404;
    }

    location = /sitemap.xml {
        try_files $uri =404;
    }

    location ~* \.(?:css|js|jpg|jpeg|png|webp|woff2?|svg|ico)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name mydoip.ru www.mydoip.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name mydoip.ru www.mydoip.ru;
    root /var/www/ebu-site;
    index index.html;
    charset utf-8;
    access_log off;

    ssl_certificate /etc/letsencrypt/live/mydoip.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydoip.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_comp_level 4;
    gzip_types text/plain text/css application/javascript application/json application/xml text/xml image/svg+xml;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /robots.txt {
        try_files $uri =404;
    }

    location = /sitemap.xml {
        try_files $uri =404;
    }

    location ~* \.(?:css|js|jpg|jpeg|png|webp|woff2?|svg|ico)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
